Error encountered:

Size: 
sizes = {
            performance_test_pb2.EMPTY: 0,
            performance_test_pb2.SMALL: 1024,
            performance_test_pb2.MEDIUM: 10240,
            performance_test_pb2.LARGE: 102400000,
            performance_test_pb2.XLARGE: 104857600}

Error:

python3 python/src/performance_client.py
Testing latency...

Latency Results:
min_latency: 1.17 ms
max_latency: 12.82 ms
avg_latency: 2.16 ms
p95_latency: 2.74 ms
p99_latency: 3.02 ms

Testing throughput with different payload sizes...

Payload size: SMALL
Messages per second: 481.33
Throughput: 0.47 MB/s
Total messages: 4814
Total data: 4.70 MB

Payload size: MEDIUM
Messages per second: 448.97
Throughput: 4.38 MB/s
Total messages: 4490
Total data: 43.85 MB

Payload size: LARGE
Traceback (most recent call last):
  File "/mnt/d/grpc-vs-rest/python/src/performance_client.py", line 174, in <module>
    main()
  File "/mnt/d/grpc-vs-rest/python/src/performance_client.py", line 149, in main
    results = client.measure_throughput(size, duration_seconds=10)
  File "/mnt/d/grpc-vs-rest/python/src/performance_client.py", line 72, in measure_throughput
    response = self.stub.UnaryCall(request)
  File "/home/tripti/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/tripti/.local/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "SERVER: Received message larger than max (102400059 vs. 10485760)"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:192.168.1.20:50051 {created_time:"2024-11-26T15:42:38.095024329-08:00", grpc_status:8, grpc_message:"SERVER: Received message larger than max (102400059 vs. 10485760)"}"


New Sizes:
